//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTbl
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> PositionId { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public Nullable<int> IsUserOfSystem { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string MaritalStatus { get; set; }
        public Nullable<double> Salary { get; set; }
    
        public virtual LocationTbl LocationTbl { get; set; }
        public virtual PositionTbl PositionTbl { get; set; }
    }
}
